# Schema for the connection configurations of the Semantic Connector module.

semantic_connector.pp_server_connection.*:
   type: config_entity
   label: 'Semantic Connector Connection'
   mapping:
     title:
       type: label
       label: 'Title'
     id:
       type: string
       label: 'ID'
     type:
       type: string
       label: 'Type'
     url:
       type: string
       label: 'URL'
     username:
       type: string
       label: 'Username'
     password:
       type: string
       label: 'Password'
     config:
       type: undefined
       label: 'Config'